package com.anbillon.debuggerview

/**
 * @author Cosouly (cosouly@gmail.com)
 */
internal object Constants {
  const val KEY_ENDPOINT_NAME = "KEY_ENDPOINT_NAME"
  const val KEY_ENDPOINT_BASE_URL = "KEY_ENDPOINT_BASE_URL"
  const val KEY_ENDPOINT_EXTRA_URL_NAME = "KEY_ENDPOINT_EXTRA_URL_NAME"
  const val KEY_ENDPOINT_EXTRA_URL = "KEY_ENDPOINT_EXTRA_URL"
  const val KEY_ENDPOINT_EXTRA_URL_DESCRIPTION = "KEY_ENDPOINT_EXTRA_URL_DESCRIPTION"
  const val KEY_ENDPOINT_CURRENT_INDEX = "KEY_ENDPOINT_CURRENT_INDEX"
  const val KEY_ENDPOINT_MOCK_DELAY_INDEX = "KEY_ENDPOINT_MOCK_DELAY_INDEX"
}
